name: Build & Test Windows

on:
  workflow_call:
  push:
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

env:
  FLY_VERSION: 0.13.2

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LLVM 20
        shell: pwsh
        run: choco install llvm --version=20.1.8 -y

      - name: Download Fly release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          gh release download v${{ env.FLY_VERSION }} `
            -R fly-lang/fly `
            -p "fly-${{ env.FLY_VERSION }}-win-x64.zip"
          Expand-Archive "fly-${{ env.FLY_VERSION }}-win-x64.zip" -DestinationPath "$env:USERPROFILE\fly"
          Add-Content $env:GITHUB_PATH "$env:USERPROFILE\fly\bin"

      - name: Build with flyp
        run: flyp build --release

      - name: Run tests
        run: flyp test
